package base;

public enum Action {
    LOGIN,
    REGISTER,
    UPDATE_SUBSCRIBER,
    SEARCH_BOOKS,
    GET_BORROW_TIMES_REPORT,
    GET_SUBSCRIBER_STATUS_REPORT,
    GET_REPORT_DATES,
    RETRIEVE_BORROWEDBOOKS
}
