package base;

public enum Action {
    LOGIN,
    REGISTER,
    UPDATE_SUBSCRIBER,
    GET_BOOK_BY_ID,
    GET_SUBSCRIBER_BY_ID,
    SEARCH_SUBSCRIBERS,
    LEND_BOOK,
    ORDER_BOOK,
    SEARCH_BOOKS,
    GET_BORROW_TIMES_REPORT,
    GET_SUBSCRIBER_STATUS_REPORT,
    GET_REPORT_DATES,
    RETRIEVE_BORROWEDBOOKS,
    EXTEND_BORROW_TIME,
    MARK_BOOK_COPY_AS_LOST
}
